# Copyright (c) 2024 Siemens AG
# This file is subject to the terms and conditions of the MIT License.
# See LICENSE file in the top-level directory.

services:
  jitter:
    image: ${REGISTRY}industrial-jitterdebugger:${TAG}
    command: ["python3", "-m", "industrial_jitterdebugger.jitter"]
    cap_add:
      - SYS_NICE
      - IPC_LOCK
    runtime: iedge
    x-resources:
      limits:
        siemens.com/isolated_core: 1
    mem_limit: 1gb
    networks:
      - industrial-jitterdebugger-net
    volumes:
      - ./publish/:/publish/
      - ./cfg-data/:/cfg-data/

  stress:
    image: ${REGISTRY}industrial-jitterdebugger:${TAG}
    command: ["python3", "-m", "industrial_jitterdebugger.stress"]
    runtime: iedge
    mem_limit: 2gb
    networks:
      - industrial-jitterdebugger-net
    volumes:
      - ./publish/:/publish/
      - ./cfg-data/:/cfg-data/
  
  industrial-jitterdebugger-webui:
    image: ${REGISTRY}industrial-jitterdebugger:${TAG}
    command: ["streamlit", "run", "/usr/bin/launch_webui.py", "--server.address=0.0.0.0", "--client.toolbarMode=minimal", "--theme.base=dark", "--theme.backgroundColor=#000028", "--theme.primaryColor=#029402"]
    mem_limit: 200mb
    networks:
      - proxy-redirect
      - industrial-jitterdebugger-net
    depends_on:
      - jitter
      - stress
    volumes:
      - ./publish/:/publish/
      - ./cfg-data/:/cfg-data/

networks:
  industrial-jitterdebugger-net:
  proxy-redirect:
    name: proxy-redirect
    external: true
    driver: bridge
